### ISSUE TITLE
[question] Is Janusweb compatibel to Oculus Quest ?

### ISSUE THREAD

**Issue by BogusCurry** [jbaicoianu/janusweb#172]
Hello ;D
A little question from me ;D

Is Janusweb compatibel to Oculus Quest ?

Greeetings
Bogus

**Comment by jbaicoianu** [comment]
Yes, JanusWeb has worked with Oculus Quest since day one, so we never really made an announcement. Maybe we should 😆

You'll have to optimize your assets well to hit the performance requirements, not every existing Janus room will automatically run on Quest, but rooms with assets that target mobile hardware capabilities should run fine.

I did another round of optimizations recently to make the underlying engine run faster on Quest too, those are all checked in to the dev release, but haven't made it to a live release yet. They will go live with 1.5 very soon.
