### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by karansher** [jbaicoianu/janusweb#56]
-need a turn on xhair option, and or a switch to free cursor mode (i.e. not locked to head). the 2d interface need to be rock solid.
-need a floor for walking and rt click to teleport like in janus native. or maybe just hotspots/anchors/vistas to click to teleport.

**Comment by jbaicoianu** [comment]
First issue is fixed in 1.1.1, this was actually just a bug with the pointer code where the cursor was being hidden by default.

Second issue is actually two issues, we can now support the right-click to teleport that we have in native, I'll I have an implementation that works as a room script, so I can convert this to be a default component in an upcoming patch release.

Player collisions with floor is a different problem, for this we need to add sphere-mesh and capsule-mesh collision handling to the physics engine.

**Comment by karansher** [comment]
Aah, thanks for the reminder I was supposed to get back to you with sphere/capsule-mesh collisions.

-karan

Ps: any idea why this does not work in janusweb. It used to (maybe I made some changes that keep it going in native but mess up on web).

http://demos.janusvr.com/karan/panosee/index.html

**Comment by jbaicoianu** [comment]
I actually have a partial implementation I started work in previously, I'll check in that code and you can see what we need to get from there to a working implementation.

**Comment by jbaicoianu** [comment]
The changelog for what I have so far is here: https://github.com/jbaicoianu/cyclone-physics-js/commit/74971c395c6c01c55886807a09ed5328c377077c

**Comment by jbaicoianu** [comment]
UX has changed a lot since this was filed, the main remaining issue is the mesh colliders which is being tracked in #197
