### ISSUE TITLE
A character object composed of several parts appears differently in JanusWeb compared to in native

### ISSUE THREAD

**Issue by DoomTay** [jbaicoianu/janusweb#84]
[Here](http://vesta.janusvr.com/nostrenz/gensokyo) is one such room where this happens

![In native client](https://user-images.githubusercontent.com/9124594/29585249-750ce074-8754-11e7-84a3-497643a6d79c.jpg)
(Her head is there, it just bounces in and out of view)

![In JanusWeb](https://user-images.githubusercontent.com/9124594/29631511-ded1904a-880d-11e7-97bb-581e2370a689.png)

It turns out that the rest of the parts are upside down underneath the ground.
![underneath](https://user-images.githubusercontent.com/9124594/29631641-4f7bd0ee-880e-11e7-897d-d986ff8abe50.png)

Also note a character standing in the back (A "ghost") is elsewhere in the area in JanusWeb

**Comment by KooIaIa** [comment]
This makes me worried there will need to be a coordinate system change. Are characters like this special circumstances in how they are organized?

**Comment by DoomTay** [comment]
Not sure. It seems the parts are all "sibling" objects.

**Comment by jbaicoianu** [comment]
Well, it's complicated.  I was actually looking into this when the bug was submitted, and it's opened a whole can of worms :)

So the main problem here is that some of the objects in the Gensokyo world have orientations set using the wrong coordinate system convention - it appears the author specified coordinates using the left-handed convention, whereas JanusWeb and Janus Native both use right-handed coordinate conventions.  So for example, one object specifies ```xdir="-1 0 0" zdir="0 0 1"```.  Both JanusWeb and Janus Native perform an orthonormalization step using these values, to make sure that xdir, ydir, and zdir represent a proper right-handed basis matrix.  So if you do the math on this, the mathematically correct answer is that in order for xdir and zdir to point in the specified direction, that means ydir must be (0,-1,0) - meaning the object would be upside down.

However, the way Native performs orthonormalization works a little bit different, and the result when run on that example set of vectors is the identity matrix, or ```xdir="1 0 0" ydir="0 1 0" zdir="0 0 1"```.  This isn't technically correct, but the result is what the author of the room intended.

I'm in the process of converting JanusWeb to use the same method as Native, but it seems to still be getting different results.  Ideally, these rotations would be fixed at the source page, in this case https://github.com/nostrenz/janusvr-touhou - I'll submit a pull request, but I'm not sure if the pages are being actively maintained at their current URLs.

**Comment by jbaicoianu** [comment]
Finally have a proper fix for this, will go out with the next release https://i.imgur.com/RUFoZQK.png
